"""Adiciona campos de hora, tutor e relacionamentos a Estadia

Revision ID: 24c8d45059b5
Revises: f7bf92ac9c3d
Create Date: 2025-09-27 20:10:59.563016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c8d45059b5'
down_revision: Union[str, Sequence[str], None] = 'f7bf92ac9c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estadia', sa.Column('tutor_id', sa.UUID(), nullable=False))
    op.add_column('estadia', sa.Column('hora_inicio', sa.Time(), nullable=False))
    op.add_column('estadia', sa.Column('hora_final', sa.Time(), nullable=True))
    
    # CORREÇÃO PARA data_entrada
    op.alter_column('estadia', 'data_entrada',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='data_entrada::date') # <-- ADICIONE ISSO

    # CORREÇÃO PARA data_saida
    op.alter_column('estadia', 'data_saida',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='data_saida::date') # <-- ADICIONE ISSO
    
    op.create_foreign_key('fk_estadia_tutor_id', 'estadia', 'tutors', ['tutor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estadia', type_='foreignkey')
    op.alter_column('estadia', 'data_saida',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('estadia', 'data_entrada',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('estadia', 'hora_final')
    op.drop_column('estadia', 'hora_inicio')
    op.drop_column('estadia', 'tutor_id')
    # ### end Alembic commands ###
