"""create estadia table

Revision ID: e75a928c984b
Revises: f375d4e08df5
Create Date: 2025-09-23 23:51:34.991531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75a928c984b'
down_revision: Union[str, Sequence[str], None] = 'f375d4e08df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estadia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('data_entrada', sa.String(), nullable=False),
    sa.Column('data_saida', sa.String(), nullable=True),
    sa.Column('valor_diaria', sa.Float(), nullable=False),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('estadia')
    # ### end Alembic commands ###
