"""Criação inicial de todas as tabelas

Revision ID: f375d4e08df5
Revises: 
Create Date: 2025-09-22 22:46:04.753272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f375d4e08df5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('especie', sa.String(), nullable=False),
    sa.Column('raca', sa.String(), nullable=False),
    sa.Column('nascimento', sa.String(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=False),
    sa.Column('vermifugado', sa.Boolean(), nullable=True),
    sa.Column('vacinado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_especie'), 'pets', ['especie'], unique=False)
    op.create_index(op.f('ix_pets_nome'), 'pets', ['nome'], unique=False)
    op.create_index(op.f('ix_pets_raca'), 'pets', ['raca'], unique=False)
    op.create_index(op.f('ix_pets_sexo'), 'pets', ['sexo'], unique=False)
    op.create_table('tutors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutors_cpf'), 'tutors', ['cpf'], unique=True)
    op.create_index(op.f('ix_tutors_name'), 'tutors', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('pet_tutor_association',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('tutor_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('pet_id', 'tutor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_tutor_association')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tutors_name'), table_name='tutors')
    op.drop_index(op.f('ix_tutors_cpf'), table_name='tutors')
    op.drop_table('tutors')
    op.drop_index(op.f('ix_pets_sexo'), table_name='pets')
    op.drop_index(op.f('ix_pets_raca'), table_name='pets')
    op.drop_index(op.f('ix_pets_nome'), table_name='pets')
    op.drop_index(op.f('ix_pets_especie'), table_name='pets')
    op.drop_table('pets')
    # ### end Alembic commands ###
