"""create pagamento table

Revision ID: f7bf92ac9c3d
Revises: e75a928c984b
Create Date: 2025-09-23 23:53:10.434873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7bf92ac9c3d'
down_revision: Union[str, Sequence[str], None] = 'e75a928c984b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagamento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('estadia_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('meio_pagamento', sa.String(), nullable=False),
    sa.Column('data_pagamento', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['estadia_id'], ['estadia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamento')
    # ### end Alembic commands ###
